main:
  - name: "Home"
    url: "/#top"
    weight: 10

  - name: "Job Market Paper"
    url: "/#job-market-paper"
    weight: 20

  - name: "Working Papers"
    url: "/#working-papers"
    weight: 30

  - name: "Contact"
    url: "/#contact"
    weight: 40

  - name: "Committee"
    url: "/#committee"
    weight: 50
